### ISSUE TITLE
Add min-width to publishing boxes

### ISSUE THREAD

**Issue by alexkingorg** [crowdfavorite/wp-social#195]
``` css
#social #respond textarea.social-input {
  min-width: 464px;
}
```

http://wordpress.org/support/topic/size-of-textarea#post-5783631
